# ==============================
# Application Info
# ==============================
spring.application.name=self-scheduling-system
server.port=${PORT:8080}

# ==============================
# MySQL Database Configuration
# ==============================
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/self_scheduling_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:Dheekshana@2026}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==============================
# JPA / Hibernate Configuration
# ==============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==============================
# Thymeleaf Configuration
# ==============================
spring.thymeleaf.cache=false